import { ShipmentRecord, ShipmentRow, ValidationIssue } from "@/lib/types";

export const demoRows: ShipmentRow[] = [
  {
    rowNumber: 2,
    externalCode: "EXT-1001",
    senderName: "上海仓 A",
    senderPhone: "13800138000",
    senderAddress: "上海市闵行区申长路 88 号",
    receiverName: "张三",
    receiverPhone: "13911112222",
    receiverAddress: "杭州市余杭区文一西路 1 号",
    weight: 12.5,
    packageCount: 3,
    temperature: "ambient",
    remark: "首批测试",
  },
  {
    rowNumber: 3,
    externalCode: "EXT-1002",
    senderName: "",
    senderPhone: "123",
    senderAddress: "上海市闵行区申长路 88 号",
    receiverName: "李四",
    receiverPhone: "13600001111",
    receiverAddress: "",
    weight: 0,
    packageCount: 1.5 as unknown as number,
    temperature: "",
    remark: "待修正",
  },
];

export const demoIssues: ValidationIssue[] = [
  { rowNumber: 3, field: "senderName", message: "必填字段缺失", level: "error" },
  { rowNumber: 3, field: "senderPhone", message: "手机号格式错误", level: "error" },
  { rowNumber: 3, field: "receiverAddress", message: "必填字段缺失", level: "error" },
  { rowNumber: 3, field: "weight", message: "重量必须为正数", level: "error" },
  { rowNumber: 3, field: "packageCount", message: "件数必须为正整数", level: "error" },
  { rowNumber: 3, field: "temperature", message: "温层必须为常温、冷藏、冷冻之一", level: "error" },
];

export const demoOrders: ShipmentRecord[] = [
  {
    id: 1,
    rowNumber: 2,
    externalCode: "EXT-1001",
    senderName: "上海仓 A",
    senderPhone: "13800138000",
    senderAddress: "上海市闵行区申长路 88 号",
    receiverName: "张三",
    receiverPhone: "13911112222",
    receiverAddress: "杭州市余杭区文一西路 1 号",
    weight: 12.5,
    packageCount: 3,
    temperature: "ambient",
    remark: "首批测试",
    importJobId: 1,
    createdAt: "2026-05-07 18:20:00",
    updatedAt: "2026-05-07 18:20:00",
  },
  {
    id: 2,
    rowNumber: 4,
    externalCode: "EXT-1005",
    senderName: "杭州分拨中心",
    senderPhone: "13700009999",
    senderAddress: "杭州市临平区运河路 9 号",
    receiverName: "王五",
    receiverPhone: "18812345678",
    receiverAddress: "南京市雨花台区软件大道 22 号",
    weight: 4.2,
    packageCount: 1,
    temperature: "chilled",
    remark: "冷藏配送",
    importJobId: 2,
    createdAt: "2026-05-07 19:12:00",
    updatedAt: "2026-05-07 19:12:00",
  },
];
