import { ShipmentRecord, ShipmentRow, ValidationIssue } from "@/lib/types";

export const demoRows: ShipmentRow[] = [
  {
    rowNumber: 2,
    externalCode: "LM-20260605-001",
    storeName: "尹三顺自助烤肉（银泰店）",
    receiverName: "",
    receiverPhone: "",
    receiverAddress: "",
    skuCode: "SKU-1001",
    skuName: "冷冻牛肉卷",
    quantity: 12,
    spec: "500g/盒",
    remark: "门店模式样例",
  },
  {
    rowNumber: 3,
    externalCode: "HN-20260605-008",
    storeName: "",
    receiverName: "李四",
    receiverPhone: "13600001111",
    receiverAddress: "长沙市雨花区万家丽中路 88 号",
    skuCode: "SKU-2209",
    skuName: "一次性餐盒",
    quantity: 36,
    spec: "300套/箱",
    remark: "收件人模式样例",
  },
  {
    rowNumber: 4,
    externalCode: "ERR-ROW",
    storeName: "",
    receiverName: "",
    receiverPhone: "123",
    receiverAddress: "",
    skuCode: "",
    skuName: "待修正物品",
    quantity: 0,
    spec: "",
    remark: "演示全量错误汇总",
  },
];

export const demoIssues: ValidationIssue[] = [
  { rowNumber: 4, field: "storeName", message: "收货门店，或收件人姓名/电话/地址至少填写一组", level: "error" },
  { rowNumber: 4, field: "receiverName", message: "收货门店，或收件人姓名/电话/地址至少填写一组", level: "error" },
  { rowNumber: 4, field: "receiverPhone", message: "手机号格式错误", level: "error" },
  { rowNumber: 4, field: "receiverAddress", message: "收货门店，或收件人姓名/电话/地址至少填写一组", level: "error" },
  { rowNumber: 4, field: "skuCode", message: "必填字段缺失", level: "error" },
  { rowNumber: 4, field: "quantity", message: "SKU发货数量必须为正数", level: "error" },
];

export const demoOrders: ShipmentRecord[] = [
  {
    id: 1,
    rowNumber: 2,
    externalCode: "LM-20260605-001",
    storeName: "尹三顺自助烤肉（银泰店）",
    receiverName: "",
    receiverPhone: "",
    receiverAddress: "",
    skuCode: "SKU-1001",
    skuName: "冷冻牛肉卷",
    quantity: 12,
    spec: "500g/盒",
    remark: "门店模式样例",
    importJobId: 1,
    createdAt: "2026-06-05 13:20:00",
    updatedAt: "2026-06-05 13:20:00",
  },
  {
    id: 2,
    rowNumber: 3,
    externalCode: "HN-20260605-008",
    storeName: "",
    receiverName: "李四",
    receiverPhone: "13600001111",
    receiverAddress: "长沙市雨花区万家丽中路 88 号",
    skuCode: "SKU-2209",
    skuName: "一次性餐盒",
    quantity: 36,
    spec: "300套/箱",
    remark: "收件人模式样例",
    importJobId: 2,
    createdAt: "2026-06-05 13:26:00",
    updatedAt: "2026-06-05 13:26:00",
  },
];
