import { ShipmentField } from "@/lib/types";

export const fieldAliasMap: Record<ShipmentField, string[]> = {
  externalCode: [
    "外部编码",
    "外部订单号",
    "客户单号",
    "订单号",
    "外部单号",
    "订单编码",
    "reference",
    "ref",
    "ref code",
    "refcode",
  ],
  senderName: ["发件人", "寄件人", "发件人姓名", "寄件人姓名", "发货人", "sender"],
  senderPhone: [
    "发件人电话",
    "发件电话",
    "寄件人电话",
    "寄件电话",
    "发货电话",
    "sender phone",
    "sender tel",
    "寄件人手机号",
  ],
  senderAddress: ["发件人地址", "发件地址", "寄件地址", "寄件人地址", "发货地址", "sender address"],
  receiverName: ["收件人", "收货人", "收方", "receiver", "receiver name", "收件人姓名"],
  receiverPhone: [
    "收件人电话",
    "收件电话",
    "收货人电话",
    "收方电话",
    "收货电话",
    "receiver phone",
    "receiver tel",
    "收件人手机号",
  ],
  receiverAddress: ["收件人地址", "收件地址", "收货地址", "收方地址", "receiver address"],
  weight: ["重量", "货重", "kg", "weight", "重量kg", "重量(kg)", "weight(kg)"],
  packageCount: ["件数", "包裹数", "数量", "packages", "count", "qty"],
  temperature: ["温层", "温区", "温控", "temperature", "温度要求", "temp zone", "tempzone"],
  remark: ["备注", "附言", "说明", "remark", "note"],
};
