import { ShipmentField } from "@/lib/types";

export const fieldAliasMap: Record<ShipmentField, string[]> = {
  externalCode: [
    "外部编码",
    "外部订单号",
    "客户单号",
    "订单号",
    "外部单号",
    "配送单号",
    "出库单号",
    "调拨单号",
    "订单编码",
    "reference",
    "ref",
    "ref code",
    "refcode",
  ],
  storeName: ["收货门店", "门店", "门店名称", "机构名称", "客户门店", "收货机构", "店铺", "store", "store name"],
  receiverName: ["收件人", "收货人", "收方", "receiver", "receiver name", "收件人姓名", "联系人"],
  receiverPhone: [
    "收件人电话",
    "收件电话",
    "收货人电话",
    "收方电话",
    "收货电话",
    "联系电话",
    "手机号码",
    "receiver phone",
    "receiver tel",
    "收件人手机号",
  ],
  receiverAddress: ["收件人地址", "收件地址", "收货地址", "收方地址", "receiver address"],
  skuCode: [
    "SKU物品编码",
    "SKU编码",
    "SKU条码",
    "外部商品编码",
    "物品编码",
    "商品编码",
    "货品编码",
    "条码",
    "编码",
    "sku",
    "sku code",
  ],
  skuName: ["SKU物品名称", "SKU名称", "物品名称", "商品名称", "货品名称", "品名", "名称", "sku name"],
  quantity: ["SKU发货数量", "发货数量", "数量", "订货数量", "配送数量", "出库数量", "qty", "quantity", "count"],
  spec: ["SKU规格型号", "规格型号", "规格", "型号", "单位", "spec"],
  remark: ["备注", "附言", "remark", "note"],
};
